import React from 'react';
import { Container, Content, NavContainer, NavItem, NavLink } from './layout.styled';
import { useRouter } from 'next/router';
import Head from 'next/head';

export const Layout = (props: React.PropsWithChildren) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <nav>
            <NavContainer>
              <NavItem>
                <NavLink href="/" $isActive={router.pathname === '/'}>
                  Home
                </NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="/admin" $isActive={router.pathname === '/admin'}>
                  Admin
                </NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="/health" $isActive={router.pathname === '/health'}>
                  Health
                </NavLink>
              </NavItem>
              <NavItem>
                <NavLink href="/settings" $isActive={router.pathname === '/settings'}>
                  Settings
                </NavLink>
              </NavItem>
            </NavContainer>
          </nav>
          <Content>{props.children}</Content>
        </Container>
      </main>
    </>
  );
};
