import React from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const Admin = dynamic(import('admin/Admin'), { ssr: false });
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const Something = dynamic(import('something/Something'), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>NEXTJS</div>
      <div>
        <Admin />
        <Something />
      </div>
    </>
  );
}
